export { ProfileForm } from './components/ProfileForm'
export { AddressCard } from './components/AddressCard'
export { AddressForm } from './components/AddressForm'
export { AddressList } from './components/AddressList'
export { useProfile } from './hooks/useProfile'
export { useAddresses } from './hooks/useAddresses'
export { profileService } from './services/profile.service'
export type { Profile, Address, ProfileWithAddresses, UpdateProfilePayload, AddressPayload } from './types/profile.types'
export type { AddressFormValues } from './components/AddressForm'
